### ISSUE TITLE
Problem with \n

### ISSUE THREAD

**Issue by mabras** [rikkit/ruby-bbcode-to-md#4]
The converter can not handle this:
```ruby
[b]

bold

[\b]
```
This is also true for other tags (like: center, i, u). the problem is with \n between the actual word (`bold` in my example) and the tags.

Thanks

**Comment by rikkit** [comment]
I'll be honest, I haven't used either this library or Ruby in over two years now. If you're up for fixing this issue though I would be happy to push it through to the gem. I'll also look at pulling in changes from @nlalonde's [fork](https://github.com/nlalonde/ruby-bbcode-to-md).

I think [this is the line](https://github.com/rikkit/ruby-bbcode-to-md/blob/master/lib/ruby-bbcode-to-md/tag_sifter.rb#L22) you'll need to change. You'll need to make this regex match tags spread over new lines - would be good to match Windows newlines as well (\r\n). 

```
'((\[ (\/)? (\w+) ((=[^\[\]]+) | (\s\w+=\w+)* | ([^\]]*))? \]) | ([^\[]+))'
```

Cheers
